
server:
  port: 6061
spring:
  cloud:
    config:
      server:
        git:
          default-label: config-server
          uri: https://github.com/lmar11xd/microservicios/tree/main/tutorial-20230905
          search-paths: config-data
  application:
    name: config-service