server:
  port: 6060
spring:
  cloud:
    config:
      server:
        git:
          default-label: gateway
          uri: https://github.com/lmar11xd/microservicios
          search-paths: config-data
  application:
    name: config-service